cloud: cloud40
lab: scalelab #scalelab/performancelab
dt_path: /root/test/architecture
compute_count: 1

# Baremetal node login and key details
ssh_password: your-password
ssh_username: cloud-admin
ssh_key_file: ~/.ssh/id_rsa #don't add .pub

# Nova migration key
nova_migration_key: ~/.ssh/nova_migration

#controlplane allocation start ip (should be same in the nncp values)
ctlplane_start_ip: 172.16.20.100

#set the kubeconfig path
ocp_environment:
  KUBECONFIG: /root/mno/kubeconfig




# External ceph vars
ceph_node_count: 3
ansible_ssh_password: "{{ ssh_password }}"

rhos_release_rpm: 
ceph_version: "7.1"

# Registry credentials used by external ceph
registry_url: "registry.redhat.io"
registry_username:
registry_password:


#provision variables
foreman_instance: https://foreman.example.com # provide foreman instance according to the lab you are using.


